Repository chartjs/chartjs-plugin-annotation, pull requests merged in 2020-10, with the labels that each got.

#224 `enabled: true` in the README.md
  README.md
Labels: documentation

#160 fixed prevent default
  .gitignore
  src/events.js
  src/helpers.js
Labels: bug, chart.js version 2

#233 Add release-drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: infrastucture

#234 Run CI on v2 branch
  .github/workflows/ci.yml
Labels: infrastructure

#235 Replace travis with actions
  .github/workflows/ci.yml
  .travis.yml
Labels: chart.js version 2, infrastructure

#236 Add release-drafter (#233)
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: chart.js version 2, infrastructure

#231 Add release workflow (with --dry-run)
  .github/workflows/npmpublish.yml
Labels: infrastructure

#237 Fix some issues detected by inspecting samples
  samples/animation.html
  samples/bar.html
  samples/box.html
  samples/bubble.html
  samples/combo-bar-line.html
  samples/horizontal-line.html
  samples/labels.html
  samples/line-logarithmic.html
  samples/line-time-scale.html
  samples/pie.html
  samples/polar-area.html
  samples/radar.html
  samples/updates.html
  src/annotation.js
  src/events.js
Labels: bug

#239 Align event hooks with to datalabels plugin
  .editorconfig
  README.md
  samples/animation.html
  samples/bar.html
  samples/box.html
  samples/bubble.html
  samples/combo-bar-line.html
  samples/horizontal-line.html
  samples/labels.html
  samples/line-logarithmic.html
  samples/line-time-scale.html
  samples/pie.html
  samples/polar-area.html
  samples/radar.html
  src/annotation.js
  src/events.js
  v3-migration.md
Labels: breaking change, enhancement
