Repository chartjs/chartjs-plugin-annotation, pull requests merged in 2020-12, with the labels that each got.

#274 Various fixes
  src/annotation.js
  src/events.js
Labels: bug

#266 Fixes events catching on rotated line labels
  src/helpers.js
  src/types/line.js
Labels: bug

#261 Add initial types
  package-lock.json
  package.json
  types/element.d.ts
  types/events.d.ts
  types/index.d.ts
  types/label.d.ts
  types/options.d.ts
  types/test/exports.ts
  types/test/tsconfig.json
Labels: types

#278 Update eslint config
  .eslintrc.yml
  package-lock.json
  package.json
Labels: infrastructure

#279 calculateLabelPosition cleanup
  src/annotation.js
  src/types/line.js
Labels: chore

#281 Add returns elements in `resyncElements`
  src/annotation.js
Labels: bug

#267 Adds cornerRadius options to box annotation
  README.md
  samples/box.html
  src/types/box.js
  v3-migration.md
Labels: enhancement

#287 Add test framework
  .eslintrc.yml
  .github/workflows/ci.yml
  karma.conf.js
  package-lock.json
  package.json
  rollup.config.js
  test/.eslintrc.yml
  test/fixtures/line/position.js
  test/fixtures/line/position.png
  test/index.js
  test/specs/line.spec.js
Labels: infrastructure
