Repository chartjs/chartjs-plugin-annotation, pull requests merged in 2020-11, with the labels that each got.

#248 Remove annotations array, using an object instead and min/max on value and endValue options
  README.md
  samples/animation.html
  samples/bar.html
  samples/box.html
  samples/bubble.html
  samples/combo-bar-line.html
  samples/horizontal-line.html
  samples/labels.html
  samples/line-logarithmic.html
  samples/line-time-scale.html
  samples/pie.html
  samples/polar-area.html
  samples/radar.html
  src/annotation.js
Labels: breaking change, bug, enhancement

#253 Chart.js v3.0.0-beta.5 compatibility
  package-lock.json
  package.json
  src/annotation.js
Labels: chore

#254 Enable Auto rotation of labels (#250)
  README.md
  samples/autoRotation.html
  src/types/line.js
Labels: enhancement

#257 Fix samples
  .eslintrc.yml
  samples/bar.html
  samples/box.html
  samples/bubble.html
  samples/combo-bar-line.html
  samples/horizontal-line.html
  samples/labels.html
  samples/line-logarithmic.html
  samples/line-time-scale.html
  samples/pie.html
  samples/polar-area.html
  samples/radar.html
  samples/updates.html
  samples/utils.js
Labels: documentation

#256 Add context to display callback (#255)
  README.md
  samples/bar.html
  src/annotation.js
Labels: breaking change, enhancement

#260 Update npmpublish.yml
  .github/workflows/npmpublish.yml
  .gitignore
Labels: infrastructure
