Repository chartjs/chartjs-plugin-annotation, pull requests merged in 2021-03, with the labels that each got.

#331 Chart.js beta.13 compatibility
  package-lock.json
  package.json
  samples/updates.html
  src/annotation.js
  src/events.js
  src/types/box.js
  src/types/ellipse.js
  src/types/line.js
  src/types/point.js
  test/specs/point.spec.js
  types/index.d.ts
  types/options.d.ts
Labels: enhancement

#340 Bump version to 1.0.0-beta.4
  package-lock.json
  package.json
Labels: chore

#341 Update badges
  README.md
Labels: chore

#346 Quote globs for consistent linting in linux
  package.json
Labels: infrastructure

#345 Fallback label.drawTime to element.drawTime
  src/annotation.js
  test/fixtures/line/label_drawTime.js
  test/fixtures/line/label_drawTime.png
Labels: bug

#342 Do not draw box border when width is 0
  src/types/box.js
  test/fixtures/box/borderWidth0.js
  test/fixtures/box/borderWidth0.png
Labels: bug

#349 Add scriptable test cases for annotation elements
  test/fixtures/box/scriptableOptions.js
  test/fixtures/box/scriptableOptions.png
  test/fixtures/ellipse/scriptableOptions.js
  test/fixtures/ellipse/scriptableOptions.png
  test/fixtures/line/labelsScriptableOptions.js
  test/fixtures/line/labelsScriptableOptions.png
  test/fixtures/line/scriptableOptions.js
  test/fixtures/line/scriptableOptions.png
  test/fixtures/point/scriptableOptions.js
  test/fixtures/point/scriptableOptions.png
Labels: enhancement

#350 Fix documentation GitHub actions
  .github/workflows/documentation.yml
  docs/static/.nojekyll
Labels: documentation

#351 Need to run from docs folder
  .github/workflows/documentation.yml
  docs/docs/interaction.md
  docs/docs/types/box.mdx
  docs/docs/types/ellipse.mdx
  docs/docs/types/line.mdx
  docs/docs/types/point.mdx
Labels: documentation

#352 Deploy as chartjs-ci user
  .github/workflows/documentation.yml
Labels: documentation

#353 Add badges to readme
  README.md
  package.json
Labels: documentation

#355 Update url text
  README.md
Labels: documentation

#354 Use the new isolated key for animations
  src/annotation.js
Labels: bug

#356 Interactive online samples using VuePress
  .github/workflows/documentation.yml
  docs/docusaurus.config.js
  old_samples/.eslintrc.yml
  old_samples/animation.html
  old_samples/autoRotation.html
  old_samples/bar.html
  old_samples/box.html
  old_samples/bubble.html
  old_samples/combo-bar-line.html
  old_samples/ellipse.html
  old_samples/horizontal-line.html
  old_samples/imageLabels.html
  old_samples/labels.html
  old_samples/line-logarithmic.html
  old_samples/line-time-scale.html
  old_samples/pie.html
  old_samples/point.html
  old_samples/polar-area.html
  old_samples/radar.html
  old_samples/updates.html
  package-lock.json
  package.json
  samples/.vuepress/config.js
  samples/.vuepress/plugins/chart-editor/components/ChartActions.vue
  samples/.vuepress/plugins/chart-editor/components/ChartEditor.vue
  samples/.vuepress/plugins/chart-editor/components/ChartView.vue
  samples/.vuepress/plugins/chart-editor/components/CodeEditor.vue
  samples/.vuepress/plugins/chart-editor/components/EditorOutput.vue
  samples/.vuepress/plugins/chart-editor/components/EditorTextarea.vue
  samples/.vuepress/plugins/chart-editor/components/Tooltip.vue
  samples/.vuepress/plugins/chart-editor/enhancer.js
  samples/.vuepress/plugins/chart-editor/global.js
  samples/.vuepress/plugins/chart-editor/index.js
  samples/.vuepress/plugins/chart-editor/styles/index.styl
  samples/.vuepress/plugins/chart-editor/styles/palette.styl
  samples/.vuepress/public/favicon.ico
  samples/.vuepress/public/favicon.png
  samples/.vuepress/public/hero.svg
  samples/.vuepress/styles/index.styl
  samples/.vuepress/styles/palette.styl
  samples/defaults.js
  samples/index.md
  samples/register.js
  samples/types/box.md
  samples/types/line.md
  samples/utils.js
Labels: documentation

#357 Fix documentation action
  .github/workflows/documentation.yml
Labels: infrastructure

#362 Link to samples from sub pages
  docs/docusaurus.config.js
Labels: documentation

#364 Switch deploy action for preserving history
  .github/workflows/documentation.yml
  docs/guide/options.md
  docs/guide/types/box.md
  docs/guide/types/ellipse.md
  docs/guide/types/line.md
  docs/guide/types/point.md
  docs/guide/usage.md
Labels: documentation, infrastructure

#365 docs deploy, use with instead of env
  .github/workflows/documentation.yml
Labels: infrastructure

#366 Add custom scriptable context
  docs/guide/options.md
  src/annotation.js
  test/fixtures/line/axis-index.js
  test/fixtures/line/axis-index.png
Labels: breaking change, enhancement

#367 Update for Chart.js v3.0.0-rc.3
  old_samples/box.html
  old_samples/ellipse.html
  old_samples/horizontal-line.html
  old_samples/imageLabels.html
  old_samples/labels.html
  old_samples/line-time-scale.html
  old_samples/point.html
  old_samples/updates.html
  package-lock.json
  package.json
  test/fixtures/box/borderDash.png
  test/fixtures/box/borderWidth0.png
  test/fixtures/box/category-index.png
  test/fixtures/box/scriptableOptions.png
  test/fixtures/ellipse/borderDash.png
  test/fixtures/ellipse/scriptableOptions.png
  test/fixtures/line/axis-index.png
Labels: enhancement

#369 Fix banner on docs
  docs/guide/banner.png
  docs/guide/index.md
Labels: documentation

#368 Extend linting to types and markdown, fix errors
  .markdownlint.yml
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
  types/.eslintrc.yml
  types/element.d.ts
  types/events.d.ts
  types/index.d.ts
  types/label.d.ts
  types/options.d.ts
  types/test/exports.ts
  types/tests/.eslintrc.yml
  types/tests/exports.ts
  types/tests/tsconfig.json
Labels: documentation, infrastructure, types

#370 Resolve element options to concrete values
  src/annotation.js
  src/types/line.js
Labels: bug

#371 Migrate to vuepress-theme-chartjs
  docs/.vuepress/config.js
  docs/.vuepress/plugins/chart-editor/components/ChartActions.vue
  docs/.vuepress/plugins/chart-editor/components/ChartEditor.vue
  docs/.vuepress/plugins/chart-editor/components/ChartView.vue
  docs/.vuepress/plugins/chart-editor/components/CodeEditor.vue
  docs/.vuepress/plugins/chart-editor/components/EditorOutput.vue
  docs/.vuepress/plugins/chart-editor/components/EditorTextarea.vue
  docs/.vuepress/plugins/chart-editor/components/Tooltip.vue
  docs/.vuepress/plugins/chart-editor/enhancer.js
  docs/.vuepress/plugins/chart-editor/global.js
  docs/.vuepress/plugins/chart-editor/index.js
  docs/.vuepress/plugins/chart-editor/styles/index.styl
  docs/.vuepress/plugins/chart-editor/styles/palette.styl
  docs/.vuepress/styles/index.styl
  docs/.vuepress/styles/palette.styl
  docs/guide/types/line.md
  package-lock.json
  package.json
Labels: documentation

#372 Bump version to 1.0.0-rc
  package-lock.json
  package.json
Labels: chore

#373 Use node 14 to build docs
  .github/workflows/documentation.yml
Labels: infrastructure

#376 Type fixes
  docs/guide/options.md
  types/events.d.ts
  types/index.d.ts
  types/options.d.ts
Labels: documentation, types

#377 Add note about registering
  README.md
Labels: documentation

#378 Skip annotations outside chartArea
  src/annotation.js
  src/helpers.js
  test/fixtures/line/out-of-range.js
  test/fixtures/line/out-of-range.png
Labels: bug

#379 Update dependencies
  package-lock.json
  package.json
Labels: chore

#380 Update vuepress-theme-chartjs
  docs/.vuepress/config.js
  package-lock.json
  package.json
Labels: documentation

#381 Add version information to charts in documentation
  docs/scripts/register.js
  karma.conf.js
  package-lock.json
  package.json
  rollup.config.js
  src/annotation.js
Labels: chore

#382 Add ellipse sample
  docs/.vuepress/config.js
  docs/samples/types/ellipse.md
  src/types/ellipse.js
Labels: documentation

#383 Add point example
  docs/.vuepress/config.js
  docs/samples/types/point.md
Labels: chore
