Repository chartjs/chartjs-plugin-annotation, pull requests merged in 2021-01, with the labels that each got.

#275 Implement a separate labelDrawTime option
  README.md
  src/annotation.js
  src/helpers.js
  src/types/box.js
  src/types/line.js
  types/label.d.ts
Labels: enhancement

#282 Maintain the label always inside the chartArea, whatever rotation has been set
  src/types/line.js
Labels: enhancement

#290 Enables display options (#289)
  src/annotation.js
Labels: bug

#291 Update dependencies and version to 1.0.0-beta
  .editorconfig
  karma.conf.js
  package-lock.json
  package.json
  rollup.config.js
  samples/.eslintrc.yml
  src/annotation.js
  src/events.js
  src/helpers.js
  src/types/box.js
  src/types/ellipse.js
  src/types/line.js
  src/types/point.js
Labels: chore, infrastructure

#293 Lint test specs, remove unused rollup plugin
  package-lock.json
  package.json
  test/fixtures/line/position.js
  test/index.js
  test/specs/line.spec.js
Labels: infrastructure

#295 Add types to package.json
  package-lock.json
  package.json
Labels: bug, types

#297 TypeScript type fixes
  README.md
  types/element.d.ts
  types/index.d.ts
  types/label.d.ts
  types/options.d.ts
  types/test/exports.ts
Labels: types

#300 Initialize always all elements even if do not show
  src/annotation.js
  test/index.js
  test/specs/display.spec.js
Labels: bug

#303 beforeDraw hook added
  README.md
  src/annotation.js
Labels: enhancement

#304 beforeDraw hook added
  README.md
  src/annotation.js
Labels: chart.js version 2, enhancement

#301 Consistently export all types
  types/index.d.ts
Labels: types

#306 Add coveralls
  .github/workflows/ci.yml
Labels: infrastructure

#305 Enable line annotation using two scales
  README.md
  samples/labels.html
  src/annotation.js
  src/helpers.js
  src/types/line.js
  test/fixtures/line/position.js
  test/fixtures/line/position.png
  test/fixtures/line/rotation.js
  test/fixtures/line/rotation.png
  v3-migration.md
Labels: breaking change, enhancement

#307 Only parse string values for scale
  src/helpers.js
  test/fixtures/box/category-index.js
  test/fixtures/box/category-index.png
  test/specs/box.spec.js
Labels: bug

#308 types modified to support beforeDraw hook
  types/options.d.ts
Labels: types

#311 Auto register/unregister annotation types
  src/annotation.js
  src/index.esm.js
  src/index.js
  types/index.d.ts
  types/test/exports.ts
  v3-migration.md
Labels: breaking change, enhancement

#312 Add tests for point annotation
  src/annotation.js
  src/events.js
  src/types/point.js
  test/fixtures/point/basic.js
  test/fixtures/point/basic.png
  test/index.js
  test/specs/point.spec.js
Labels: infrastructure

#310 Update deps, bump version
  karma.conf.js
  package-lock.json
  package.json
Labels: chore

#317 Moves color option out of font namespace
  README.md
  src/types/line.js
  types/label.d.ts
Labels: breaking change

#322 Ignores no-display elements during events management
  src/events.js
  test/specs/events.spec.js
Labels: bug

#325 Applies element defaults before resolving element properties
  README.md
  samples/point.html
  src/annotation.js
  src/types/box.js
  src/types/ellipse.js
  src/types/line.js
  test/specs/point.spec.js
Labels: enhancement
