Repository chartjs/chartjs-plugin-annotation, pull requests merged in 2021-08, with the labels that each got.

#448 Add missing animations prop to options interface.
  types/options.d.ts
Labels: types

#451 Pass event instance to listeners
  docs/guide/interaction.md
  src/events.js
  types/events.d.ts
Labels: enhancement

#453 LabelOptions.width and .height are optional
  types/label.d.ts
Labels: types

#454 Prevent infinity in line example, unused utils
  docs/samples/charts/bar.md
  docs/samples/types/line.md
Labels: chore

#455 Prevent error when removing data in point sample
  docs/samples/types/point.md
Labels: documentation
