Repository chartjs/chartjs-plugin-annotation, pull requests merged in 2021-02, with the labels that each got.

#327 Internal options merged, resolved and stored into the state
  README.md
  src/annotation.js
  src/events.js
  src/types/line.js
  test/specs/point.spec.js
Labels: enhancement

#328 Chart.js beta.10 update
  package-lock.json
  package.json
  types/index.d.ts
Labels: types

#329 Enables borderDash and borderDashOffset options to all annotations
  README.md
  src/types/box.js
  src/types/ellipse.js
  src/types/line.js
  src/types/point.js
  test/fixtures/box/borderDash.js
  test/fixtures/box/borderDash.png
  test/fixtures/ellipse/borderDash.js
  test/fixtures/ellipse/borderDash.png
  test/fixtures/point/borderDash.js
  test/fixtures/point/borderDash.png
  test/specs/ellipse.spec.js
  types/options.d.ts
Labels: enhancement

#330 Enables the label content to be an Image.
  README.md
  samples/imageLabels.html
  samples/img/chartjs-logo.svg
  src/types/line.js
  types/label.d.ts
Labels: enhancement

#335 Use annotation defaults when resolving options
  src/annotation.js
Labels: bug
