Repository chartjs/chartjs-plugin-annotation, pull requests merged in 2021-12, with the labels that each got.

#505 Fix line annotation documentation
  docs/guide/types/line.md
Labels: documentation

#506 Enable label padding as object
  docs/guide/options.md
  docs/guide/types/box.md
  docs/guide/types/label.md
  docs/guide/types/line.md
  src/types/box.js
  src/types/label.js
  src/types/line.js
  test/fixtures/box/labelPadding.js
  test/fixtures/box/labelPadding.png
  test/fixtures/label/padding.js
  test/fixtures/label/padding.png
  test/fixtures/line/padding.js
  test/fixtures/line/padding.png
  test/fixtures/line/paddingXY.js
  test/fixtures/line/paddingXY.png
  types/label.d.ts
Labels: enhancement

#517 Add missing options to types definition
  test/fixtures/line/partial-range.js
  types/events.d.ts
  types/label.d.ts
  types/options.d.ts
Labels: types

#503 Add POLYGON annotation
  docs/.vuepress/config.js
  docs/guide/types/polygon.md
  docs/samples/types/polygon.md
  src/annotation.js
  src/helpers.js
  src/types/point.js
  src/types/polygon.js
  test/fixtures/polygon/borderDash.js
  test/fixtures/polygon/borderDash.png
  test/fixtures/polygon/decagon.js
  test/fixtures/polygon/decagon.png
  test/fixtures/polygon/heptagon.js
  test/fixtures/polygon/heptagon.png
  test/fixtures/polygon/hexagon.js
  test/fixtures/polygon/hexagon.png
  test/fixtures/polygon/nonagon.js
  test/fixtures/polygon/nonagon.png
  test/fixtures/polygon/octagon.js
  test/fixtures/polygon/octagon.png
  test/fixtures/polygon/pentagon.js
  test/fixtures/polygon/pentagon.png
  test/fixtures/polygon/rhombus.js
  test/fixtures/polygon/rhombus.png
  test/fixtures/polygon/rotation.js
  test/fixtures/polygon/rotation.png
  test/fixtures/polygon/scriptableOptions.js
  test/fixtures/polygon/scriptableOptions.png
  test/fixtures/polygon/square.js
  test/fixtures/polygon/square.png
  test/fixtures/polygon/triangle.js
  test/fixtures/polygon/triangle.png
  test/specs/polygon.spec.js
  types/options.d.ts
Labels: enhancement

#518 Throw error when non-existing scale id is used
  karma.conf.js
  src/annotation.js
  test/fixtures/box/missingScale.js
  test/fixtures/box/missingScale.png
  test/specs/scales.spec.js
Labels: documentation

#519 Move annotation types handling to types/index.js
  src/annotation.js
  src/types/index.js
Labels: chore

#526 Log a warning instead of throwing when non-existing scale id is used
  src/annotation.js
  test/fixtures/box/missingScale.js
  test/fixtures/box/missingScale.png
  test/specs/scales.spec.js
Labels: bug

#523 Add clip option
  docs/.vuepress/config.js
  docs/guide/configuration.md
  src/annotation.js
  test/fixtures/label/clip-false.js
  test/fixtures/label/clip-false.png
  types/options.d.ts
  types/tests/exports.ts
Labels: enhancement

#520 Add test cases to coverage all events cases
  test/events.js
  test/fixtures/label/borderDash.js
  test/index.js
  test/specs/box.spec.js
  test/specs/display.spec.js
  test/specs/ellipse.spec.js
  test/specs/events.spec.js
  test/specs/label.spec.js
  test/specs/line.spec.js
  test/specs/point.spec.js
  test/specs/polygon.spec.js
Labels: infrastructure

#530 Log warning when unknown annotation type is used
  src/annotation.js
  test/index.js
  test/specs/annotation.spec.js
Labels: bug

#529 Run event tests on plugin and annotation levels
  test/events.js
Labels: infrastructure

#528 Use the context of element for events dispatching
  src/annotation.js
  src/events.js
  test/events.js
Labels: enhancement, performance

#527 Add point positioning by box options for point, polygon and label annotations
  docs/guide/types/label.md
  docs/guide/types/point.md
  docs/guide/types/polygon.md
  src/helpers.js
  src/types/box.js
  src/types/ellipse.js
  src/types/label.js
  src/types/point.js
  src/types/polygon.js
  test/fixtures/label/boxLocation.js
  test/fixtures/label/boxLocation.png
  test/fixtures/point/boxLocation.js
  test/fixtures/point/boxLocation.png
  test/fixtures/point/boxLocationRadius.js
  test/fixtures/point/boxLocationRadius.png
  test/fixtures/polygon/boxLocation.js
  test/fixtures/polygon/boxLocation.png
  test/fixtures/polygon/boxLocationRadius.js
  test/fixtures/polygon/boxLocationRadius.png
  types/options.d.ts
Labels: enhancement

#536 Add note about clip option usage and events catching
  docs/guide/configuration.md
Labels: documentation

#542 Enforce unix linebreaks
  .eslintrc.yml
  .gitattributes
  docs/samples/types/label.md
  docs/samples/types/polygon.md
  src/types/label.js
Labels: infrastructure

#541 Enable label annotation animations
  docs/guide/types/box.md
  docs/guide/types/label.md
  docs/samples/types/label.md
  src/annotation.js
  src/helpers.js
  src/helpers/helpers.canvas.js
  src/helpers/helpers.chart.js
  src/helpers/helpers.core.js
  src/helpers/helpers.geometric.js
  src/helpers/helpers.options.js
  src/helpers/index.js
  src/types/box.js
  src/types/label.js
  src/types/point.js
  test/events.js
  test/specs/label.spec.js
Labels: bug

#543 Add random seed reporting to test runs
  karma.conf.js
  test/seed-reporter.js
Labels: infrastructure

#544 Resolve circulare dependencies
  src/helpers/helpers.canvas.js
  src/helpers/helpers.chart.js
  src/helpers/helpers.core.js
  src/helpers/helpers.options.js
Labels: chore

#538 Add samples to the documentation
  docs/.vuepress/config.js
  docs/samples/box/basic.md
  docs/samples/box/disclosure.md
  docs/samples/box/quarters.md
  docs/samples/ellipse/basic.md
  docs/samples/ellipse/rotation.md
  docs/samples/intro.md
  docs/samples/label/basic.md
  docs/samples/label/callout.md
  docs/samples/label/lowerUpper.md
  docs/samples/label/point.md
  docs/samples/line/animation.md
  docs/samples/line/average.md
  docs/samples/line/basic.md
  docs/samples/line/datasetBars.md
  docs/samples/line/labelVisibility.md
  docs/samples/line/limited.md
  docs/samples/line/lowerUpper.md
  docs/samples/line/standardDeviation.md
  docs/samples/line/visibility.md
  docs/samples/point/basic.md
  docs/samples/point/combined.md
  docs/samples/polygon/basic.md
  docs/samples/polygon/stop.md
Labels: documentation

#546 Fix random test failures
  package.json
  src/helpers/helpers.canvas.js
  test/fixtures/label/boxLocation.js
  test/fixtures/label/boxLocation.png
Labels: infrastructure

#548 Disclosure box sample is made responsive
  docs/samples/box/disclosure.md
Labels: documentation

#550 Fix `isBoundToPoint` function implementation
  src/helpers/helpers.options.js
  test/fixtures/point/boundToPoint0.js
  test/fixtures/point/boundToPoint0.png
  test/fixtures/polygon/boundToPoint0.js
  test/fixtures/polygon/boundToPoint0.png
Labels: bug

#547 Make a consistent implementations of `inRange` in all annotations
  docs/samples/line/lowerUpper.md
  src/types/ellipse.js
  src/types/label.js
  src/types/line.js
  src/types/point.js
  src/types/polygon.js
  test/fixtures/line/paddingXY.png
Labels: bug

#551 Add `xAdjust` and `yAdjust` options to point and polygon annotations
  docs/.vuepress/config.js
  docs/guide/types/point.md
  docs/guide/types/polygon.md
  docs/samples/point/outsideChartArea.md
  docs/samples/polygon/outsideChartArea.md
  src/helpers/helpers.chart.js
  src/types/point.js
  src/types/polygon.js
  test/fixtures/point/adjust.js
  test/fixtures/point/adjust.png
  test/fixtures/point/boxLocationAdjust.js
  test/fixtures/point/boxLocationAdjust.png
  test/fixtures/polygon/adjust.js
  test/fixtures/polygon/adjust.png
  test/fixtures/polygon/boxLocationAdjust.js
  test/fixtures/polygon/boxLocationAdjust.png
  test/fixtures/polygon/invalidSides.js
  test/fixtures/polygon/invalidSides.png
  test/specs/point.spec.js
  test/specs/polygon.spec.js
  types/options.d.ts
Labels: enhancement

#554 Enable label `position` as percentage of the size
  docs/guide/types/box.md
  docs/guide/types/label.md
  docs/guide/types/line.md
  docs/samples/line/labelVisibility.md
  src/helpers/helpers.options.js
  src/types/box.js
  src/types/label.js
  src/types/line.js
  test/fixtures/box/labelPosition.js
  test/fixtures/box/labelPosition.png
  test/fixtures/label/positionHorizontalPercentage.js
  test/fixtures/label/positionHorizontalPercentage.png
  test/fixtures/label/positionVerticalPercentage.js
  test/fixtures/label/positionVerticalPercentage.png
  test/fixtures/line/positionPercent.js
  test/fixtures/line/positionPercent.png
  types/label.d.ts
Labels: enhancement

#560 Fix `animations` option type and add missing documentation
  docs/guide/configuration.md
  types/options.d.ts
Labels: bug, documentation, types

#561 Bump version to 1.2.0, update dependencies
  package-lock.json
  package.json
Labels: chore

#564 Chore/remove old samples
  old_samples/.eslintrc.yml
  old_samples/animation.html
  old_samples/autoRotation.html
  old_samples/bar.html
  old_samples/box.html
  old_samples/bubble.html
  old_samples/combo-bar-line.html
  old_samples/ellipse.html
  old_samples/horizontal-line.html
  old_samples/imageLabels.html
  old_samples/labels.html
  old_samples/line-logarithmic.html
  old_samples/line-time-scale.html
  old_samples/pie.html
  old_samples/point.html
  old_samples/polar-area.html
  old_samples/radar.html
  old_samples/updates.html
  package.json
Labels: chore

#566 Build docs before releasing as latest/next
  .github/workflows/npmpublish.yml
Labels: bug, documentation

#568 Remove point nodes from label annotations in the test cases
  test/fixtures/label/positionHorizontalPercentage.js
  test/fixtures/label/positionVerticalPercentage.js
  test/fixtures/point/adjust.js
  test/fixtures/point/boxLocationAdjust.js
  test/fixtures/polygon/adjust.js
  test/fixtures/polygon/boxLocationAdjust.js
Labels: infrastructure

#567 Publish latest/next docs in separate job
  .github/workflows/npmpublish.yml
Labels: infrastructure

#569 Add integration tests (ts)
  .github/workflows/ci.yml
  .github/workflows/documentation.yml
  .github/workflows/npmpublish.yml
  package-lock.json
  package.json
  test/integration/.eslintrc.yml
  test/integration/integration-test.js
  test/integration/ts/basic.ts
  test/integration/ts/package.json
  test/integration/ts/test.js
  test/integration/ts/tsconfig.json
  types/label.d.ts
Labels: bug, infrastructure, types

#573 Increase the integration test timeout to 5 min
  test/integration/integration-test.js
Labels: infrastructure

#575 Workaround for array syntax bug with Chart.js<v3.7
  src/annotation.js
  src/types/label.js
  test/fixtures/label/borderDash.js
  test/fixtures/label/calloutSide.js
Labels: bug

#576 Bump version to 1.2.1
  package-lock.json
  package.json
Labels: chore

#574 Move scale management functions to a dedicated file
  src/annotation.js
  src/scale.js
Labels: chore

#570 Sort default options alphabetically
  src/annotation.js
  src/types/box.js
  src/types/ellipse.js
  src/types/line.js
  src/types/point.js
  src/types/polygon.js
Labels: chore

#571 Store drawable elements to the state
  src/annotation.js
Labels: performance

#578 Fix complexity and duplicated code on scale management
  src/scale.js
  test/fixtures/box/adjustScaleFalse.js
  test/fixtures/box/adjustScaleFalse.png
  test/fixtures/box/adjustScaleIgnore.js
  test/fixtures/box/adjustScaleIgnore.png
  test/fixtures/box/adjustScaleMax.js
  test/fixtures/box/adjustScaleMax.png
  test/fixtures/box/adjustScaleMin.js
  test/fixtures/box/adjustScaleMin.png
Labels: chore

#584 Change `var` to `const` in the samples
  docs/samples/box/basic.md
  docs/samples/box/disclosure.md
  docs/samples/box/quarters.md
  docs/samples/charts/bar.md
  docs/samples/charts/line.md
  docs/samples/ellipse/basic.md
  docs/samples/ellipse/rotation.md
  docs/samples/intro.md
  docs/samples/label/basic.md
  docs/samples/label/callout.md
  docs/samples/label/lowerUpper.md
  docs/samples/label/point.md
  docs/samples/line/animation.md
  docs/samples/line/average.md
  docs/samples/line/basic.md
  docs/samples/line/labelVisibility.md
  docs/samples/line/lowerUpper.md
  docs/samples/line/standardDeviation.md
  docs/samples/point/basic.md
  docs/samples/polygon/basic.md
  docs/samples/polygon/stop.md
Labels: documentation

#582 Remove undefined event listeners from state if disabled at runtime
  src/events.js
  test/events.js
Labels: bug

#583 Fix events catching on rotated ellipse annotations
  src/types/ellipse.js
  test/specs/ellipse.spec.js
Labels: bug

#586 new annotation types added to ElementOptionsByType
  types/index.d.ts
Labels: types

#588 Fix event test case for rotated ellipse annotation
  test/specs/ellipse.spec.js
Labels: infrastructure

#587 Add borderJoinStyle round to the road signals sample
  docs/samples/polygon/stop.md
Labels: documentation

#591 Properly consider the line thickness in the intersect calculation
  src/types/line.js
  test/specs/line.spec.js
Labels: bug

#596 Place `performance` commits under Development
  .github/release-drafter.yml
Labels: infrastructure

#595 Fix dynamically showing/hiding line label
  src/annotation.js
  src/helpers/helpers.canvas.js
  src/helpers/helpers.options.js
  src/types/box.js
  src/types/label.js
  src/types/line.js
  src/types/point.js
  test/fixtures/box/label-dynamic.js
  test/fixtures/box/label-dynamic.png
  test/fixtures/line/label-dynamic-hide.js
  test/fixtures/line/label-dynamic-hide.png
  test/fixtures/line/label-dynamic-show.js
  test/fixtures/line/label-dynamic-show.png
Labels: bug

#592 Bump version to 1.2.2, update deps
  package-lock.json
  package.json
Labels: chore

#598 Normalize border style setting
  src/types/ellipse.js
  src/types/line.js
Labels: chore

#599 Use PI constant of Chartjs helpers instead of Math.PI
  src/types/ellipse.js
  src/types/line.js
Labels: chore

#603 Fixes events triggering on the label of a line annotation
  src/types/line.js
  test/specs/line.spec.js
Labels: bug

#604 Add JSDoc to `labelIsVisible` method of line annotation
  src/types/line.js
Labels: chore

#605 Remove renaming the imports from chartjs.helpers of callback function
  src/events.js
Labels: chore

#606 Sort alphabetically the options definitions in the documentation
  docs/guide/configuration.md
  docs/guide/types/box.md
  docs/guide/types/ellipse.md
  docs/guide/types/label.md
  docs/guide/types/line.md
  docs/guide/types/polygon.md
Labels: documentation
