Repository chartjs/chartjs-plugin-annotation, pull requests merged in 2021-04, with the labels that each got.

#384 Depend on chart.js v3.0.0
  package-lock.json
  package.json
Labels: chore

#385 Depend on chart.js v3.0.1
  package-lock.json
  package.json
Labels: bug

#386 Enables textAlign option to line label
  docs/guide/types/line.md
  src/types/line.js
  types/label.d.ts
Labels: enhancement

#392 Insane timeouts for insanely slow actions
  karma.conf.js
Labels: infrastructure

#390 Add sample on bar chart
  docs/.vuepress/config.js
  docs/samples/charts/bar.md
Labels: documentation

#389 Lint markdown with eslint, fix errors, update deps
  .eslintrc.yml
  .markdownlint.yml
  docs/guide/options.md
  docs/samples/types/box.md
  docs/samples/types/ellipse.md
  docs/samples/types/point.md
  package-lock.json
  package.json
Labels: infrastructure

#393 Update option typings, fix `type`
  src/annotation.js
  types/label.d.ts
  types/options.d.ts
  types/tests/exports.ts
Labels: bug, types

#394 Bump version to 1.0.0
  package-lock.json
  package.json
Labels: chore

#395 Remove --dry-run from publish action
  .github/workflows/npmpublish.yml
Labels: infrastructure

#403 Restrict mouse events to where the line actually is
  src/types/line.js
Labels: bug

#404 Update LabelPosition type to match v1.0.0
  types/label.d.ts
Labels: types

#406 Update installation instructions
  docs/guide/index.md
Labels: documentation

#409 Remove sourcemap
  rollup.config.js
Labels: bug, infrastructure

#415 Add warning about registration to Getting Started
  docs/guide/index.md
Labels: documentation

#416 Add coveralls.io badge
  README.md
Labels: infrastructure

#417 Add fixtures for cornerRadius
  test/fixtures/box/cornerRadius.js
  test/fixtures/box/cornerRadius.png
Labels: infrastructure

#414 Fix drawing of lines with points out of chartArea
  src/helpers.js
  src/types/line.js
  test/fixtures/box/partial-range.js
  test/fixtures/box/partial-range.png
  test/fixtures/ellipse/partial-range.js
  test/fixtures/ellipse/partial-range.png
  test/fixtures/line/direction-reverse.js
  test/fixtures/line/direction-reverse.png
  test/fixtures/line/direction.js
  test/fixtures/line/direction.png
  test/fixtures/line/partial-range.js
  test/fixtures/line/partial-range.png
Labels: bug

#420 Bump version to 1.0.1
  package-lock.json
  package.json
Labels: chore
