Repository chartjs/chartjs-plugin-annotation, pull requests merged in 2021-11, with the labels that each got.

#471 Typings for default settings on element
  types/index.d.ts
Labels: types

#476 Fix the point annotation documentation guide
  docs/guide/types/point.md
Labels: documentation

#479 Fix linting of types (and errors)
  types/.eslintrc.yml
  types/element.d.ts
  types/events.d.ts
  types/label.d.ts
  types/options.d.ts
Labels: infrastructure

#475 Use font.lineHeight instead of font.size for labelling in line annotation
  src/types/line.js
  test/fixtures/line/label-border.png
  test/fixtures/line/label_drawTime.png
  test/fixtures/line/labelsScriptableOptions.png
  test/fixtures/line/position.png
  test/fixtures/line/rotation.png
  test/fixtures/line/scriptableOptions.png
Labels: bug

#485 Fix type for CoreAnnotationOptions.borderDash
  types/options.d.ts
Labels: bug, types

#486 Bump version to 1.1.0, update deps
  .github/workflows/ci.yml
  .github/workflows/documentation.yml
  .github/workflows/npmpublish.yml
  package-lock.json
  package.json
Labels: chore

#489 Update last node version in actions
  .github/workflows/npmpublish.yml
Labels: infrastructure

#490 Fix syntax error from previous commit
  .github/workflows/npmpublish.yml
Labels: infrastructure

#492 Documentation versioning
  .github/workflows/documentation.yml
  .github/workflows/npmpublish.yml
  docs/.vuepress/config.js
  package-lock.json
  package.json
  scripts/docs-config.sh
Labels: documentation, infrastructure

#493 Add executable bit to docs-config.sh
  .github/workflows/documentation.yml
  scripts/docs-config.sh
Labels: infrastructure

#496 Add v0.5.7 readme
  0.5.7/README.md
Labels: documentation

#500 Add border* options documentation and types for the label in the line annotation
  docs/guide/types/line.md
  types/label.d.ts
Labels: documentation

#499 Fix broken 'View this example' link
  README.md
Labels: documentation

#502 Add LABEL annotation and label node to BOX annotation
  docs/.vuepress/config.js
  docs/guide/types/box.md
  docs/guide/types/label.md
  docs/samples/types/box.md
  docs/samples/types/label.md
  src/annotation.js
  src/helpers.js
  src/types/box.js
  src/types/ellipse.js
  src/types/label.js
  src/types/line.js
  src/types/point.js
  test/fixtures/box/label.js
  test/fixtures/box/label.png
  test/fixtures/box/labelMultiline.js
  test/fixtures/box/labelMultiline.png
  test/fixtures/box/missingScale.js
  test/fixtures/box/missingScale.png
  test/fixtures/label/borderDash.js
  test/fixtures/label/borderDash.png
  test/fixtures/label/borderRadius.js
  test/fixtures/label/borderRadius.png
  test/fixtures/label/boxNotVisible.js
  test/fixtures/label/boxNotVisible.png
  test/fixtures/label/contentMultiline.js
  test/fixtures/label/contentMultiline.png
  test/fixtures/label/positionHorizontal.js
  test/fixtures/label/positionHorizontal.png
  test/fixtures/label/positionVertical.js
  test/fixtures/label/positionVertical.png
  test/fixtures/label/scriptableOptions.js
  test/fixtures/label/scriptableOptions.png
  test/specs/label.spec.js
  types/label.d.ts
  types/options.d.ts
Labels: enhancement
