Repository chartjs/chartjs-plugin-annotation, pull requests merged in 2021-09, with the labels that each got.

#459 Add border support for line label
  docs/guide/types/box.md
  docs/guide/types/line.md
  docs/samples/charts/bar.md
  docs/samples/types/box.md
  docs/samples/types/ellipse.md
  docs/samples/types/line.md
  old_samples/box.html
  src/types/box.js
  src/types/line.js
  test/fixtures/box/cornerRadius.js
  test/fixtures/line/label-border.js
  test/fixtures/line/label-border.png
  types/label.d.ts
  types/options.d.ts
Labels: enhancement

#458 Hide line-annotations completely outside chartArea
  docs/.vuepress/config.js
  docs/samples/charts/line.md
  src/types/line.js
Labels: bug

#460 docs: typo YMax -> yMax
  docs/guide/types/box.md
  docs/guide/types/ellipse.md
  docs/guide/types/line.md
Labels: documentation

#456 Add rotation support for ellipse annotations
  docs/guide/types/ellipse.md
  docs/samples/types/ellipse.md
  src/types/ellipse.js
  test/fixtures/ellipse/rotation.js
  test/fixtures/ellipse/rotation.png
Labels: enhancement
