Repository chartjs/chartjs-plugin-annotation, pull requests merged in 2022-05, with the labels that each got.

#730 Remove test job from windows runner
  .github/workflows/ci.yml
Labels: infrastructure

#630 Move element fallback to plugins.annotation.common
  src/annotation.js
  src/types/index.js
  test/fixtures/line/label_drawTime.js
  test/fixtures/line/label_drawTime.png
  test/specs/annotation.spec.js
Labels: bug, breaking change

#727 Enable line annotation label as label sub-element
  docs/guide/migrationV2.md
  docs/samples/line/labelVisibility.md
  src/annotation.js
  src/types/box.js
  src/types/label.js
  src/types/line.js
  test/fixtures/line/label-dynamic-hide.js
  test/fixtures/line/label-dynamic-show.js
  test/fixtures/line/labelShadowColors.js
  test/specs/line.spec.js
Labels: breaking change

#733 Add documentation and type for 'common' plugin option
  docs/guide/configuration.md
  docs/guide/migrationV2.md
  docs/samples/box/quarters.md
  docs/samples/line/labelVisibility.md
  docs/samples/line/limited.md
  docs/samples/point/combined.md
  docs/samples/point/outsideChartArea.md
  docs/samples/polygon/outsideChartArea.md
  types/options.d.ts
  types/tests/exports.ts
Labels: documentation, types

#731 Callout position calculated when label is drawn
  docs/.vuepress/config.js
  docs/samples/interaction/dragging.md
  docs/samples/interaction/interaction.md
  src/types/label.js
Labels: enhancement

#734 Change tests configuration using new 'common' plugin option
  test/fixtures/line/labelsScriptableOptions.js
  test/fixtures/line/scriptableOptions.js
  test/fixtures/polygon/hexagonWithPoints.js
Labels: chore

#737 Add point option to polygon annotation options type
  types/options.d.ts
Labels: types

#735 Improve usage of rotation option in callout management
  src/types/label.js
Labels: chore

#736 Move interaction object at top level of plugin options
  docs/guide/configuration.md
  src/annotation.js
  types/options.d.ts
  types/tests/exports.ts
Labels: chore

#738 Add z option to all annotations
  docs/guide/types/box.md
  docs/guide/types/ellipse.md
  docs/guide/types/label.md
  docs/guide/types/line.md
  docs/guide/types/point.md
  docs/guide/types/polygon.md
  src/annotation.js
  src/types/box.js
  src/types/ellipse.js
  src/types/label.js
  src/types/line.js
  src/types/point.js
  src/types/polygon.js
  test/fixtures/box/zIndex.js
  test/fixtures/box/zIndex.png
  test/fixtures/line/labelZindex.js
  test/fixtures/line/labelZindex.png
  types/label.d.ts
  types/options.d.ts
Labels: enhancement

#742 Use margin option in the callout check for being shown
  src/types/label.js
  test/fixtures/label/calloutNoShown.js
  test/fixtures/label/calloutNoShown.png
Labels: bug

#743 Reduce complexity for resolving the label callout position
  src/types/label.js
Labels: chore

#747 Adds common annotation options section in the documentation
  docs/.vuepress/config.js
  docs/guide/types/_commonOptions.md
  docs/guide/types/box.md
  docs/guide/types/ellipse.md
  docs/guide/types/label.md
  docs/guide/types/line.md
  docs/guide/types/point.md
  docs/guide/types/polygon.md
  package-lock.json
  package.json
Labels: documentation

#751 Add sample how to select annotations
  docs/.vuepress/config.js
  docs/samples/interaction/dragging.md
  docs/samples/interaction/selection.md
Labels: documentation

#752 Update line annotation diagram to describe new element structure
  docs/diagrams/elementLineProps.drawio
  docs/guide/migrationV2.md
  docs/img/elementLineProps.png
Labels: documentation
