Repository chartjs/chartjs-plugin-annotation, pull requests merged in 2022-08, with the labels that each got.

#780 Fix typo
  test/events.js
Labels: chore

#790 Manage line label visibility when chart is zooming or panning
  src/types/label.js
  src/types/line.js
Labels: bug

#791 Bump to version 2.0.1
  package-lock.json
  package.json
Labels: chore

#793 Add id option documentation to all annotations
  docs/guide/types/_commonOptions.md
  docs/guide/types/box.md
  docs/guide/types/ellipse.md
  docs/guide/types/label.md
  docs/guide/types/line.md
  docs/guide/types/point.md
  docs/guide/types/polygon.md
Labels: documentation
