Repository chartjs/chartjs-plugin-annotation, pull requests merged in 2022-07, with the labels that each got.

#771 Add API docs
  .github/release-drafter.yml
  .gitignore
  docs/.vuepress/config.js
  package-lock.json
  package.json
  tsconfig.json
Labels: documentation

#764 Remove label clipping to box annotation size
  docs/guide/migrationV2.md
  src/annotation.js
  src/types/box.js
  src/types/label.js
  test/fixtures/box/labelMultiline.png
  test/fixtures/box/labelPadding.png
Labels: breaking change

#777 Bump to version 2.0.0
  package-lock.json
  package.json
Labels: chore
