Repository chartjs/chartjs-plugin-annotation, pull requests merged in 2022-04, with the labels that each got.

#709 Add migration guide v2 section to getting started page
  docs/.vuepress/config.js
  docs/guide/migrationV2.md
Labels: documentation

#678 Use scale defined in the chart when x/y ScaleID options are not set
  docs/guide/migrationV2.md
  docs/guide/types/box.md
  docs/guide/types/ellipse.md
  docs/guide/types/label.md
  docs/guide/types/line.md
  docs/guide/types/point.md
  docs/guide/types/polygon.md
  src/helpers/helpers.chart.js
  src/scale.js
  src/types/box.js
  src/types/ellipse.js
  src/types/label.js
  src/types/line.js
  src/types/point.js
  src/types/polygon.js
  test/fixtures/box/noDefaultScales.js
  test/fixtures/box/noDefaultScales.png
  test/fixtures/ellipse/noDefaultScales.js
  test/fixtures/ellipse/noDefaultScales.png
  test/fixtures/label/noDefaultScales.js
  test/fixtures/label/noDefaultScales.png
  test/fixtures/line/noDefaultScales.js
  test/fixtures/line/noDefaultScales.png
  test/fixtures/point/noDefaultScales.js
  test/fixtures/point/noDefaultScales.png
  test/fixtures/polygon/noDefaultScales.js
  test/fixtures/polygon/noDefaultScales.png
Labels: enhancement, breaking change

#655 Enable stacked scales and with reverse option support
  docs/guide/migrationV2.md
  docs/guide/types/label.md
  docs/guide/types/point.md
  docs/guide/types/polygon.md
  src/helpers/helpers.chart.js
  src/types/line.js
  test/fixtures/box/missingXMinMax.js
  test/fixtures/box/missingXMinMax.png
  test/fixtures/box/missingXMinMaxCategory.js
  test/fixtures/box/missingXMinMaxCategory.png
  test/fixtures/box/missingXMinMaxCategoryReverse.js
  test/fixtures/box/missingXMinMaxCategoryReverse.png
  test/fixtures/box/missingY2MinMaxStacked.js
  test/fixtures/box/missingY2MinMaxStacked.png
  test/fixtures/box/missingYMinMax.js
  test/fixtures/box/missingYMinMax.png
  test/fixtures/box/missingYMinMaxReverse.js
  test/fixtures/box/missingYMinMaxReverse.png
  test/fixtures/box/missingYMinMaxStacked.js
  test/fixtures/box/missingYMinMaxStacked.png
  test/fixtures/label/missingValuesStacked.js
  test/fixtures/label/missingValuesStacked.png
  test/fixtures/line/missingValuesStacked.js
  test/fixtures/line/missingValuesStacked.png
  test/fixtures/line/missingYMinMax.js
  test/fixtures/line/missingYMinMax.png
  test/fixtures/point/missingValuesStacked.js
  test/fixtures/point/missingValuesStacked.png
  test/fixtures/polygon/missingValuesStacked.js
  test/fixtures/polygon/missingValuesStacked.png
Labels: enhancement, breaking change

#659 Enable interaction mode support for events
  docs/guide/configuration.md
  docs/guide/migrationV2.md
  docs/guide/options.md
  src/annotation.js
  src/events.js
  src/helpers/helpers.core.js
  src/interaction.js
  src/types/box.js
  src/types/ellipse.js
  src/types/label.js
  src/types/line.js
  src/types/point.js
  src/types/polygon.js
  test/index.js
  test/specs/box.spec.js
  test/specs/ellipse.spec.js
  test/specs/label.spec.js
  test/specs/line.spec.js
  test/specs/point.spec.js
  test/specs/polygon.spec.js
  test/utils.js
  types/options.d.ts
  types/tests/exports.ts
Labels: enhancement, breaking change

#701 Remove cornerRadius option from box and line annotations
  docs/guide/migrationV2.md
  src/helpers/helpers.canvas.js
  src/types/box.js
  src/types/line.js
  types/label.d.ts
  types/options.d.ts
Labels: breaking change

#702 Remove x/yPadding options from the label of line annotation
  docs/guide/migrationV2.md
  docs/guide/types/line.md
  src/types/line.js
  test/fixtures/line/paddingXY.js
  test/fixtures/line/paddingXY.png
  types/label.d.ts
  types/options.d.ts
Labels: breaking change

#706 Normalize annotations elements to be based on common box model
  docs/diagrams/elementBoxProps.drawio
  docs/diagrams/elementEllipseProps.drawio
  docs/diagrams/elementLabelProps.drawio
  docs/diagrams/elementLineProps.drawio
  docs/diagrams/elementPointProps.drawio
  docs/diagrams/elementPolygonProps.drawio
  docs/guide/configuration.md
  docs/guide/migrationV2.md
  docs/img/elementBoxProps.png
  docs/img/elementEllipseProps.png
  docs/img/elementLabelProps.png
  docs/img/elementLineProps.png
  docs/img/elementPointProps.png
  docs/img/elementPolygonProps.png
  src/annotation.js
  src/helpers/helpers.canvas.js
  src/helpers/helpers.chart.js
  src/helpers/helpers.core.js
  src/helpers/helpers.geometric.js
  src/types/box.js
  src/types/ellipse.js
  src/types/label.js
  src/types/line.js
  src/types/point.js
  src/types/polygon.js
  test/specs/box.spec.js
  test/specs/ellipse.spec.js
  test/specs/label.spec.js
  test/specs/line.spec.js
  test/specs/point.spec.js
  test/specs/polygon.spec.js
  types/element.d.ts
Labels: breaking change

#716 Remove dblclick hook to prepare chart redrawing from an event hook
  docs/guide/configuration.md
  docs/guide/migrationV2.md
  src/annotation.js
  src/events.js
  test/events.js
  test/specs/events.spec.js
  types/events.d.ts
  types/options.d.ts
Labels: breaking change

#717 Enable event handlers to indicate chart should be re-drawn
  docs/guide/configuration.md
  docs/samples/line/labelVisibility.md
  src/annotation.js
  src/events.js
  test/fixtures/box/label-dynamic.js
  test/fixtures/line/arrowHeadsDeleteAtRuntime.js
  test/fixtures/line/label-dynamic-hide.js
  test/fixtures/line/label-dynamic-show.js
  types/events.d.ts
Labels: enhancement

#719 Change default interaction options in chart defaults for the samples
  docs/scripts/defaults.js
Labels: documentation

#720 Reduce visibility of some line annotation element methods
  docs/guide/migrationV2.md
  src/types/label.js
  src/types/line.js
Labels: breaking change

#721 Add sample about interaction options
  docs/.vuepress/config.js
  docs/samples/interaction.md
Labels: documentation

#723 Require at least chartjs v3.7
  docs/guide/migrationV2.md
  package-lock.json
  package.json
  src/annotation.js
Labels: breaking change, chore

#724 Update min version req in readme
  README.md
Labels: documentation

#722 Add JSDoc to exported functions
  src/elements.js
  src/events.js
  src/helpers/helpers.canvas.js
  src/helpers/helpers.chart.js
  src/helpers/helpers.core.js
  src/helpers/helpers.options.js
  src/interaction.js
  src/scale.js
  types/element.d.ts
Labels: documentation

#725 Enable box annotation label as label sub-element
  docs/guide/migrationV2.md
  docs/samples/interaction.md
  src/annotation.js
  src/types/box.js
  src/types/label.js
  test/fixtures/box/label-dynamic.js
  types/element.d.ts
Labels: enhancement, breaking change
