Repository chartjs/chartjs-plugin-annotation, pull requests merged in 2022-01, with the labels that each got.

#607 Remove `point` node from label annotation sample
  docs/samples/label/point.md
Labels: documentation

#609 Update labelVisibility sample to demonstrate different approaches
  docs/samples/line/labelVisibility.md
Labels: documentation

#612 Sort shadow color default options alphabetically
  src/types/box.js
  src/types/ellipse.js
  src/types/label.js
  src/types/line.js
  src/types/point.js
  src/types/polygon.js
Labels: chore

#613 Enable the link to label configuration from the guide navigation menu
  docs/guide/types/box.md
  docs/guide/types/line.md
  docs/guide/types/polygon.md
Labels: documentation

#616 Add specific test cases for ellipse annotation event handling
  test/specs/ellipse.spec.js
Labels: chore

#617 Remove `readValueToProps` function of options helpers
  src/helpers/helpers.options.js
Labels: chore

#614 Improve event handling adding test cases
  src/events.js
  test/events.js
  test/specs/events.spec.js
Labels: chore

#627 Fix the scale limit update when annotation value is 0
  src/scale.js
  test/fixtures/line/out-of-range-value0.js
  test/fixtures/line/out-of-range-value0.png
Labels: bug

#628 Fix the default options values in the documentation
  docs/guide/types/box.md
  docs/guide/types/line.md
Labels: documentation

#619 Properly consider the border thickness on the annotations' events
  src/helpers/helpers.core.js
  src/types/box.js
  src/types/ellipse.js
  src/types/label.js
  src/types/line.js
  src/types/point.js
  src/types/polygon.js
  test/events.js
  test/specs/box.spec.js
  test/specs/ellipse.spec.js
  test/specs/events.spec.js
  test/specs/label.spec.js
  test/specs/line.spec.js
  test/specs/lineLabel.spec.js
  test/specs/point.spec.js
  test/specs/polygon.spec.js
Labels: enhancement

#633 Remove not used default route for backgroundColor option in label annotation
  src/types/label.js
Labels: chore

#632 Box: change event tests to inRange tests
  test/index.js
  test/specs/box.spec.js
  test/utils.js
Labels: chore

#555 Enable sub elements
  docs/guide/types/box.md
  docs/guide/types/label.md
  docs/guide/types/line.md
  docs/guide/types/point.md
  docs/guide/types/polygon.md
  docs/samples/polygon/basic.md
  src/annotation.js
  src/helpers/helpers.chart.js
  src/helpers/helpers.core.js
  src/helpers/helpers.geometric.js
  src/types/box.js
  src/types/point.js
  src/types/polygon.js
  test/fixtures/box/label.js
  test/fixtures/box/label.png
  test/fixtures/box/labelMultiline.js
  test/fixtures/box/labelMultiline.png
  test/fixtures/box/labelPadding.js
  test/fixtures/box/labelPadding.png
  test/fixtures/polygon/hexagonWithPoints.js
  test/fixtures/polygon/hexagonWithPoints.png
  test/index.js
  test/specs/helpers.spec.js
Labels: enhancement

#634 Box: test borderWidths. Ellipse: change events tests to inRange tests
  src/helpers/helpers.geometric.js
  src/types/ellipse.js
  test/specs/box.spec.js
  test/specs/ellipse.spec.js
Labels: chore

#635 Fix auto callout position calculation in label annotation
  src/types/label.js
  test/fixtures/label/calloutHorizontalPosition.js
  test/fixtures/label/calloutHorizontalPosition.png
  test/fixtures/label/calloutOverlapLabel.js
  test/fixtures/label/calloutVerticalPosition.js
  test/fixtures/label/calloutVerticalPosition.png
Labels: bug

#638 Chart.js < v3.7 warning instead of exception
  src/annotation.js
  src/helpers/helpers.core.js
  test/specs/helpers.spec.js
Labels: chore

#637 Tests: use helper function to fetch elements
  test/events.js
  test/fixtures/box/label-dynamic.js
  test/fixtures/line/arrowHeadsDeleteAtRuntime.js
  test/fixtures/line/label-dynamic-hide.js
  test/fixtures/line/label-dynamic-show.js
  test/index.js
  test/specs/box.spec.js
  test/specs/ellipse.spec.js
  test/utils.js
Labels: chore

#639 Remove old test cases
  test/specs/display.spec.js
  test/specs/point.spec.js
Labels: chore

#640 Label fixtures: remove point tests, update padding
  test/fixtures/label/calloutPoint.js
  test/fixtures/label/calloutPoint.png
  test/fixtures/label/calloutPointStyle.js
  test/fixtures/label/calloutPointStyle.png
  test/fixtures/label/calloutStylingPoint.js
  test/fixtures/label/calloutStylingPoint.png
  test/fixtures/label/padding.js
  test/fixtures/label/padding.png
  test/fixtures/label/positionVerticalAndPoint.js
  test/fixtures/label/positionVerticalAndPoint.png
  test/index.js
  test/utils.js
Labels: chore

#641 Label fixtures: combine border tests to one file
  test/fixtures/label/border.js
  test/fixtures/label/border.png
  test/fixtures/label/borderDash.js
  test/fixtures/label/borderDash.png
  test/fixtures/label/borderRadius.js
  test/fixtures/label/borderRadius.png
Labels: chore

#643 Label fixtures: merge position tests in vertical and horizontal ones
  test/fixtures/label/positionHorizontal.js
  test/fixtures/label/positionHorizontal.png
  test/fixtures/label/positionHorizontalAndPoint.js
  test/fixtures/label/positionHorizontalAndPoint.png
  test/fixtures/label/positionHorizontalPercentage.js
  test/fixtures/label/positionHorizontalPercentage.png
  test/fixtures/label/positionVertical.js
  test/fixtures/label/positionVertical.png
  test/fixtures/label/positionVerticalPercentage.js
  test/fixtures/label/positionVerticalPercentage.png
Labels: chore

#644 Add tests for missing and empty label content
  test/fixtures/label/contentMultiline.js
Labels: chore

#645 Label fixtures: merge missing scales test cases
  test/fixtures/label/missingBothScales.js
  test/fixtures/label/missingBothScales.png
  test/fixtures/label/missingScales.js
  test/fixtures/label/missingScales.png
  test/fixtures/label/missingXScale.js
  test/fixtures/label/missingXScale.png
  test/fixtures/label/missingYScale.js
  test/fixtures/label/missingYScale.png
Labels: chore

#648 Label: change event tests to inRange tests
  test/specs/label.spec.js
Labels: chore

#647 Label fixtures: merge canvas test cases and remove useless point test
  test/fixtures/label/canvas.js
  test/fixtures/label/canvas.png
  test/fixtures/label/canvasSizeChanged.js
  test/fixtures/label/canvasSizeChanged.png
  test/fixtures/label/stylingPoint.js
  test/fixtures/label/stylingPoint.png
Labels: chore

#649 Point: change event tests to inRange tests
  test/specs/ellipse.spec.js
  test/specs/point.spec.js
Labels: chore

#651 Polygon: change event tests to inRange tests
  src/types/polygon.js
  test/specs/polygon.spec.js
Labels: chore

#654 Fix wrong dataset index in sample
  docs/samples/line/datasetBars.md
Labels: documentation

#650 Move events test cases to events.spec
  test/events.js
  test/index.js
  test/specs/events.spec.js
  test/specs/line.spec.js
  test/specs/lineLabel.spec.js
Labels: chore

#653 Directly assign new element resolved properties
  src/annotation.js
  test/fixtures/box/gradientBackground.js
  test/fixtures/box/gradientBackground.png
  test/index.js
  test/specs/box.spec.js
  test/specs/ellipse.spec.js
  test/specs/events.spec.js
  test/specs/label.spec.js
  test/specs/point.spec.js
  test/specs/polygon.spec.js
  test/utils.js
Labels: bug

#657 Line: change event tests to inRange tests
  src/types/line.js
  test/specs/line.spec.js
Labels: chore

#661 Bump version to 1.3.0, update deps
  karma.conf.js
  package-lock.json
  package.json
Labels: chore

#663 Documentation updates
  docs/guide/types/line.md
Labels: documentation
