Repository chartjs/chartjs-plugin-annotation, pull requests merged in 2023-05, with the labels that each got.

#877 Fix compile errors when using multiple plugins
  types/index.d.ts
Labels: bug

#838 Set the plugin as module
  README.md
  docs/.vuepress/config.ts
  docs/guide/index.md
  docs/guide/integration.md
  docs/guide/migrationV1.md
  docs/guide/migrationV2.md
  docs/guide/migrationV3.md
  docs/index.md
  karma.conf.cjs
  package-lock.json
  package.json
  rollup.config.js
  scripts/docs-config.sh
  src/annotation.js
  test/integration/integration-test.js
  test/integration/node-commonjs/package.json
  test/integration/node-commonjs/test.js
  test/integration/node-module/package.json
  test/integration/node-module/test.js
  test/integration/ts/package.json
  test/seed-reporter.js
Labels: breaking change, chore

#883 Bump to version 3.0.0
  package-lock.json
  package.json
  test/integration/node-commonjs/package.json
  test/integration/node-module/package.json
  test/integration/ts/package.json
Labels: chore

#885 Fix documentation after setting plugin as module
  docs/.vuepress/config.ts
Labels: bug, documentation

#888 Bump to version 3.0.1
  package-lock.json
  package.json
Labels: chore
